retailpulse:
  target: dev

  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: retailpulse
      schema: silver
      threads: 4